name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth-service, catalog-service, patient-appointment-service, billing-service]
      fail-fast: false          

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      working-directory: ${{ matrix.service }}
      run: npm ci

    - name: Security audit (npm)
      id: audit
      working-directory: ${{ matrix.service }}
      run: |
        npm audit --audit-level=moderate --json > audit-report.json
        cat audit-report.json | jq '.metadata.vulnerabilities'
    
    - name: Upload audit report
      if: always()                           
      uses: actions/upload-artifact@v4
      with:
        name: audit-${{ matrix.service }}
        path: ${{ matrix.service }}/audit-report.json

    - name: Run tests
      working-directory: ${{ matrix.service }}
      run: npm test -- --runInBand
